apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: perms-learn
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      serviceAccountName: perm-learn-cloudrun-sa@my-generic-project-504019.iam.gserviceaccount.com
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/my-generic-project-504019/cloud-run-source-deploy/jshairbray-perms-learn/perms-learn:ad87c3213f616ab98cb5cf09e666ad923d73f0ea
        name: placeholder-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
  traffic:
  - percent: 100
    latestRevision: true